### ISSUE TITLE
Tul sok a TODO

### ISSUE THREAD

**Issue by notyasuomain-cmd** [nyila7/Dusza2023-24#1]
segics

**Comment by nyila7** [comment]
Too bad!

**Comment by notyasuomain-cmd** [comment]
Tul ora lesz!

**Comment by nyila7** [comment]
![image](https://github.com/nyila7/Dusza2023-24/assets/53142540/e9f9aceb-2390-446f-9274-c1c75c189f14)

**Comment by nyila7** [comment]
> Tul ora lesz!

:(

**Comment by nyila7** [comment]
-![410912342_3608605636093515_3169504328182926944_n.png](https://github.com/nyila7/Dusza2023-24/assets/53142540/b8126f34-4c89-4c1c-a933-4d58553349fd)

**Comment by notyasuomain-cmd** [comment]
keves a fizetesem

**Comment by notyasuomain-cmd** [comment]
engedjetek ki a pincebol pls
