### ISSUE TITLE
Felugró ablak nem látszik azonnal

### ISSUE THREAD

**Issue by fergaljon** [nyila7/Dusza2023-24#3]
Fogadásnál vagy játék létrehozásnál a felugró ablak a jelenlegi mögé kerül, és így nem látszik. Ezt mihamarabb orvosolni kell.

**Comment by notyasuomain-cmd** [comment]
10p

**Comment by notyasuomain-cmd** [comment]
Elvileg kijavitottam, nekem linuxon mashogy mukodik
probald ki remelem windowson is jo
