### ISSUE TITLE
Sorozatos fogadás nem működik

### ISSUE THREAD

**Issue by fergaljon** [nyila7/Dusza2023-24#4]
Ha egy fogadó egymás után kétszer akar fogadni, nem működik.

**Comment by notyasuomain-cmd** [comment]
Pontosan mikor nem mukodik?
En ugylatom hogy szepen irja a fogadasok.txt-be tobb fogadas leadasakor is

**Comment by nyila7** [comment]
Az esemenyek_sorszam es az alanyok_sorszam line_num-ot vár, sorszám volt megadva
